module.exports = {
  "accessor-pairs": "off",
  "array-callback-return": "off",
  "block-scoped-var": "off",
  "complexity":"off",
  "class-methods-use-this": "off",
  "consistent-return": "off",
  "curly": "off",
  "default-case": "off",
  "dot-notation": "off",
  "dot-location":"off",
  "eqeqeq":"off",
  "guard-for-in": "off",
  "no-alert": "off",
  "no-caller": "off",
  "no-case-declarations": "off",
  "no-div-regex": "off",
  "no-else-return": "off",
  "no-empty-function":"off",
  "no-empty-pattern": "off",
  "no-eq-null": "off",
  "no-eval": "off",
  "no-extend-native": "off",
  "no-extra-bind": "off",
  "no-extra-label": "off",
  "no-fallthrough":"off",
  "no-floating-decimal": "off",
  "no-global-assign":"off",
  "no-native-reassign": "off",
  "no-implicit-coercion":"off",
  "no-implicit-globals": "off",
  "no-implied-eval": "off",
  "no-invalid-this": "off",
  "no-iterator": "off",
  "no-labels":"off",
  "no-lone-blocks": "off",
  "no-loop-func": "off",
  "no-magic-numbers":"off",
  "no-multi-spaces":"off",
  "no-multi-str": "off",
  "no-new": "off",
  "no-new-func": "off",
  "no-new-wrappers": "off",
  "no-octal": "off",
  "no-octal-escape": "off",
  "no-param-reassign":"off",
  "no-proto": "off",
  "no-redeclare": "off",
  "no-restricted-properties":"off",
  "no-return-assign":"off",
  "no-return-await": "off",
  "no-script-url": "off",
  "no-self-assign": "off",
  "no-self-compare": "off",
  "no-sequences": "off",
  "no-throw-literal": "off",
  "no-unmodified-loop-condition": "off",
  "no-unused-expressions":"off",
  "no-unused-labels": "off",
  "no-useless-call": "off",
  "no-useless-concat": "off",
  "no-useless-escape": "off",
  "no-useless-return": "off",
  "no-void": "off",
  "no-warning-comments":"off",
  "no-with": "off",
  "prefer-promise-reject-errors":"off",
  "radix": "off",
  "require-await": "off",
  "vars-on-top": "off",
  "wrap-iife":"off",
  "yoda": "off",
  "for-direction": "off",
  "getter-return":"off",
  "no-await-in-loop": "off",
  "no-compare-neg-zero": "off",
  "no-cond-assign":"off",
  "no-console":"off",
  "no-constant-condition": "off",
  "no-control-regex": "off",
  "no-debugger": "off",
  "no-dupe-args": "off",
  "no-dupe-keys": "off",
  "no-duplicate-case": "off",
  "no-empty": "off",
  "no-empty-character-class": "off",
  "no-ex-assign": "off",
  "no-extra-boolean-cast": "off",
  "no-extra-parens":"off",
  "no-extra-semi": "off",
  "no-func-assign": "off",
  "no-inner-declarations": "off",
  "no-invalid-regexp": "off",
  "no-irregular-whitespace": "off",
  "no-obj-calls": "off",
  "no-prototype-builtins": "off",
  "no-regex-spaces": "off",
  "no-sparse-arrays": "off",
  "no-template-curly-in-string": "off",
  "no-unexpected-multiline": "off",
  "no-unreachable": "off",
  "no-unsafe-finally": "off",
  "no-unsafe-negation": "off",
  "no-negated-in-lhs": "off",
  "use-isnan": "off",
  "valid-jsdoc": "off",
  "valid-typeof":"off",
  "callback-return": "off",
  "global-require": "off",
  "handle-callback-err": "off",
  "no-buffer-constructor": "off",
  "no-mixed-requires":"off",
  "no-new-require": "off",
  "no-path-concat": "off",
  "no-process-env": "off",
  "no-process-exit": "off",
  "no-restricted-modules": "off",
  "no-sync": "off",
  "array-bracket-newline":"off",
  "array-element-newline":"off",
  "array-bracket-spacing":"off",
  "block-spacing":"off",
  "brace-style":"off",
  "camelcase":"off",
  "capitalized-comments":"off",
  "comma-dangle":"off",
  "comma-spacing":"off",
  "comma-style":"off",
  "computed-property-spacing":"off",
  "consistent-this": "off",
  "eol-last":"off",
  "func-call-spacing":"off",
  "func-name-matching":"off",
  "func-names":"off",
  "func-style":"off",
  "function-paren-newline":"off",
  "id-blacklist": "off",
  "id-length": "off",
  "id-match": "off",
  "indent":"off",
  "jsx-quotes":"off",
  "key-spacing":"off",
  "keyword-spacing":"off",
  "line-comment-position":"off",
  "linebreak-style":"off",
  "lines-around-comment": "off",
  "lines-around-directive":"off",
  "max-depth":"off",
  "max-len":"off",
  "max-lines":"off",
  "max-nested-callbacks": "off",
  "max-params":"off",
  "max-statements":"off",
  "max-statements-per-line":"off",
  "multiline-ternary":"off",
  "new-cap":"off",
  "new-parens": "off",
  "newline-after-var": "off",
  "newline-before-return": "off",
  "newline-per-chained-call":"off",
  "no-array-constructor": "off",
  "no-bitwise": "off",
  "no-continue": "off",
  "no-inline-comments": "off",
  "no-lonely-if": "off",
  "no-mixed-operators":"off",
  "no-mixed-spaces-and-tabs": "off",
  "no-multi-assign":"off",
  "no-multiple-empty-lines":"off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-new-object": "off",
  "no-plusplus":"off",
  "no-restricted-syntax":"off",
  "no-spaced-func": "off",
  "no-tabs": "off",
  "no-ternary": "off",
  "no-trailing-spaces":"off",
  "no-underscore-dangle":"off",
  "no-unneeded-ternary":"off",
  "no-whitespace-before-property": "off",
  "nonblock-statement-body-position": "off",
  "object-curly-spacing":"off",
  "object-curly-newline":"off",
  "object-property-newline":"off",
  "one-var":"off",
  "one-var-declaration-per-line":"off",
  "operator-assignment":"off",
  "operator-linebreak": "off",
  "padded-blocks":"off",
  "padding-line-between-statements": "off",
  "quote-props":"off",
  "quotes":"off",
  "require-jsdoc": "off",
  "semi":"off",
  "semi-spacing":"off",
  "semi-style":"off",
  "sort-keys":"off",
  "sort-vars": "off",
  "space-before-blocks": "off",
  "space-before-function-paren":"off",
  "space-in-parens":"off",
  "space-infix-ops": "off",
  "space-unary-ops":"off",
  "spaced-comment":"off",
  "switch-colon-spacing":"off",
  "template-tag-spacing":"off",
  "unicode-bom":"off",
  "wrap-regex": "off",
  "init-declarations": "off",
  "no-catch-shadow": "off",
  "no-delete-var": "off",
  "no-label-var": "off",
  "no-restricted-globals":"off",
  "no-shadow": "off",
  "no-shadow-restricted-names": "off",
  "no-undef": "off",
  "no-undef-init": "off",
  "no-undefined": "off",
  "no-unused-vars":"off",
  "no-use-before-define":"off",
  "arrow-body-style":"off",
  "arrow-parens":"off",
  "arrow-spacing":"off",
  "constructor-super": "off",
  "generator-star-spacing":"off",
  "no-class-assign": "off",
  "no-confusing-arrow":"off",
  "no-const-assign": "off",
  "no-dupe-class-members": "off",
  "no-duplicate-imports": "off",
  "no-new-symbol": "off",
  "no-restricted-imports": "off",
  "no-this-before-super": "off",
  "no-useless-computed-key": "off",
  "no-useless-constructor": "off",
  "no-useless-rename":"off",
  "no-var": "off",
  "object-shorthand":"off",
  "prefer-arrow-callback":"off",
  "prefer-const":"off",
  "prefer-destructuring":"off",
  "prefer-numeric-literals": "off",
  "prefer-reflect": "off",
  "prefer-rest-params": "off",
  "prefer-spread": "off",
  "prefer-template": "off",
  "require-yield": "off",
  "rest-spread-spacing":"off",
  "sort-imports":"off",
  "symbol-description": "off",
  "template-curly-spacing": "off",
  "yield-star-spacing":"off",
  "import/no-unresolved":"off",
  "import/named": "off",
  "import/default": "off",
  "import/namespace": "off",
  "import/export": "off",
  "import/no-named-as-default": "off",
  "import/no-named-as-default-member": "off",
  "import/no-deprecated": "off",
  "import/no-extraneous-dependencies":"off",
  "import/no-mutable-exports": "off",
  "import/no-commonjs": "off",
  "import/no-amd": "off",
  "import/no-nodejs-modules": "off",
  "import/first":"off",
  "import/imports-first": "off",
  "import/no-duplicates": "off",
  "import/no-namespace": "off",
  "import/extensions":"off",
  "import/order":"off",
  "import/newline-after-import": "off",
  "import/prefer-default-export":"off",
  "import/no-restricted-paths": "off",
  "import/max-dependencies":"off",
  "import/no-absolute-path": "off",
  "import/no-dynamic-require": "off",
  "import/no-internal-modules":"off",
  "import/unambiguous": "off",
  "import/no-webpack-loader-syntax": "off",
  "import/no-unassigned-import": "off",
  "import/no-named-default": "off",
  "import/no-anonymous-default-export":"off",
  "strict": "off"
}
